### ISSUE TITLE
d-h.st broken

### ISSUE THREAD

**Issue by Arsyadi** [HandyUserscripts/AntiAdware#10]
example link http://d-h.st/vp3
![D-h.st Fake Download Button](http://s22.postimg.org/ji2an0dap/2015_01_20_140913.png)

**Comment by devnoname120** [comment]
I cannot reproduce your issue.

Which version of AntiAdware are you using? On which browser with which Userscript manager?

**Comment by Arsyadi** [comment]
AntiAdware 1.28.1, firefox 35.0 & using greasemonkey.

**Comment by devnoname120** [comment]
Please do the following:
1. Right-click on the fake button and then on 'inspect element', and give me a screenshot of the code
2. Press Ctrl + Shift + J, and give me the information related to AntiAdware.

**Comment by Arsyadi** [comment]
Sorry for late reply.
Its working now after reinstalling greasemonkey. I think it caused by greasemonkey can not handle some script, but who knows.. 
You can close this case.
