### ISSUE TITLE
SourceForge is not working right now?

### ISSUE THREAD

**Issue by thx1200** [HandyUserscripts/AntiAdware#12]
Downloading FileZilla gave me the SourceForge adware installer: http://sourceforge.net/projects/filezilla/?source=typ_redirect

**Comment by devnoname120** [comment]
I cannot reproduce your issue. Are you sure that AntiAdware is running and up-to-date ?
If you downloaded it from OpenUserJS, it might be outdated. Try to download it from Github instead.

**Comment by Martii** [comment]
FileZilla, not to mention SourceForge *(SF)* shouldn't be doing any kind of adware installation... Since I've contributed to that project before I would actually appreciate knowing the detailed Steps to Reproduce.

**Comment by devnoname120** [comment]
SourceForge is known to allow developers to make users retrive the program by using a download manager. In this download manager, a handful of PUPs are installed, if users do not carefully skip every offer.

FileZilla employs this opportunity in order to earn money.

**Comment by Martii** [comment]
Interesting... I'll have to see where that is under my account there... everytime I download Filezilla it just comes from my selected mirror with no adware.... now the installer may try to do something but it's been a while since I've done a clean installation and not an upgrade.

**Comment by devnoname120** [comment]
Try to delete Sourceforge's cookies, it might be the reason.
