### ISSUE TITLE
Optionally Create an Account on OUJS

### ISSUE THREAD

**Issue by Martii** [HandyUserscripts/AntiAdware#13]
To address your issue mentioned at OpenUserJs/OpenUserJS.org#599 you could create an account on OUJS with this GH account and optionally put the following in your metadata block:

``` javascript
// @oujs:author HandyUserscripts
// @oujs:contributor devnoname120
```

... which currently let's another authorized OUJS account **contributor** be able to **edit** the source on OUJS.... however the GH web hook sync needs to be set up on this GH account and the OUJS account sync for automatic syncing. Please note these keys may be changing their name and position at some point in the near future. *(few edits as I'm still in my morning... :)*

**Comment by devnoname120** [comment]
> you could create an account on OUJS with this GH account

Do you mean that I should create an OUJS account from the HandyUserscripts organization?
If so, then I do not think that I can do it since the organization is not an account, and does not have credentials, for all I know.

**Comment by Martii** [comment]
Sizzle set up our Organization so I'm not entirely sure how these work on GH. If there aren't credentials then we can't create the account without GH authorization of ownership... but there is some historical chatter at OpenUserJS/OpenUserJS.org#231 . I'll try to look at it this evening when I'm at dev capable machine and see if OUJS can sync to my account... but importing versus syncing are two different things. Basically when GH sends the webhook the owner is @HandyUserscripts which has to coincide with an OUJS account with that in `ghUsername`... so @devnoname120 will never be able to sync with this repo on OUJS.

**Comment by devnoname120** [comment]
You could check the owners of the organization for deciding whether the repository should be sync'ed or not.

Thank you for your support!

**Comment by devnoname120** [comment]
I removed OpenUserJS some time ago because of this issue, and since there is not update, I will close this issue.
