### ISSUE TITLE
180upload.com

### ISSUE THREAD

**Issue by SMed79** [HandyUserscripts/AntiAdware#14]
Hi, 
i think 180upload need to be update http://180upload.com/e9s4rusbmy22

![adware 180upload.com](http://i.imgur.com/c2rxOie.png)

Thanks.

**Comment by devnoname120** [comment]
I cannot reproduce your issue, can you please tell me which browser and Userscripts Engine you do use?

**Comment by SMed79** [comment]
Hi, 
OS: Manjaro Linux
Userscripts: anti-adblock-killer, adsbypasser and AntiAdware.
Browser Firefox v37.0.1 and Chromium v41.0.2272.118

**Comment by devnoname120** [comment]
Never mind, I thought I already had pushed an update since I fixed this issue.

4b75463dd2062df4841ad604464315f860c95096
