### ISSUE TITLE
uptobox.com Download Manager Adware

### ISSUE THREAD

**Issue by axarad** [HandyUserscripts/AntiAdware#16]
Hello and thank you very much for this wonderful script,
I want to inform you that file hosting website www.uptobox.com has started showing Download Manager Adware link instead of the "REAL" download link and pushing people to register to get the direct link...
(check this link for example to see yourself: http://uptobox.com/rekfubw9huwg)
Please help us and fix it as soon as you can because this is a very popular file hosting website.
I really appreciate your work
Thanks a lot again!

**Comment by devnoname120** [comment]
Hello, thank you for your request.
I will add support for Uptobox in about 2 weeks, because I do not have access to a computer right now.

Related issue: https://greasyfork.org/en/forum/discussion/3983/x

**Comment by axarad** [comment]
I understand, thanks for responding & for your efforts!

**Comment by devnoname120** [comment]
I am unable to see any download manager on Uptobox right now.
If they ever show again, please reopen this issue, and provide me the source of the page.

**Comment by axarad** [comment]
Hi,
Download manager button is showing
here is an example of download link: http://uptobox.com/ib4i3u1vpoc3
and here is what I get:[img]http://i.imgur.com/MMPI5i2.jpg[/img]

**Comment by devnoname120** [comment]
I still cannot see it.
Can you please provide me the source of the page?

**Comment by devnoname120** [comment]
I still cannot see it.
Can you please provide me the source of the page?

**Comment by axarad** [comment]
Tested and working!
Thank you very much for your hard work!
