### ISSUE TITLE
rapidrar.com

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [HandyUserscripts/AntiAdware#18]
rapidrar.com has a countdown that is not disabled.  It was disabled but I guess they caught on and now it isn't.

Example link: http://rapidrar.com/zyk8mix7gzqo

**Comment by devnoname120** [comment]
I cannot find any Adware.
Please post this issue on a relevant script, for instance [AdsBypasser](https://github.com/adsbypasser/adsbypasser/).
