### ISSUE TITLE
Datafilehost in Broken

### ISSUE THREAD

**Issue by axarad** [HandyUserscripts/AntiAdware#20]
Hi,
I want to inform you that Datafilehost.com is broken,
In fact when I click on "download" button it gives a link for "Adware" instead of the real download link
Testing link: http://www.datafilehost.com/d/0d40bf39
![untitled1](https://cloud.githubusercontent.com/assets/10789454/8391354/29ffe486-1cb8-11e5-802c-1489a09f3e0d.jpg)
![untitled](https://cloud.githubusercontent.com/assets/10789454/8391355/2ecff65e-1cb8-11e5-9c30-309c9b8f809a.jpg)
Thank you!

**Comment by devnoname120** [comment]
Thank you for the report.
This has been fixed in version v1.35.1.
