### ISSUE TITLE
Fake download buttons @ media1fire.com

### ISSUE THREAD

**Issue by MED-PRO** [HandyUserscripts/AntiAdware#21]
Hi,
I've noticed that this file sharing website has some fake download buttons not covered by adblock (Easylist) which may trick users to download adware (screenshot)
Can you guys remove them?
Thank you
Tested link: http://up.media1fire.com/j7h3rkt12tjd
![untitled](https://cloud.githubusercontent.com/assets/10789454/9427880/43c5cc5a-498b-11e5-9736-3192ec87feb6.jpg)

**Comment by devnoname120** [comment]
This issue has been fixed in version v1.35.2.

**Comment by MED-PRO** [comment]
I updated to 1.35.2 but nothing has changed, fake buttons still there!

**Comment by devnoname120** [comment]
Sorry for the issue, this should be fixed in version v1.35.3.

**Comment by MED-PRO** [comment]
The issue is fixed now thank you!
