### ISSUE TITLE
Add support for go4up.com (Mulit-Uploader)

### ISSUE THREAD

**Issue by MED-PRO** [HandyUserscripts/AntiAdware#22]
Hi
Fake download button on: http://go4up.com/rd/* (screenshot)
Tested link: http://go4up.com/rd/4c9b78e5dde6/50
Thank you!
![untitled](https://cloud.githubusercontent.com/assets/10789454/9429001/501a3e9a-49b9-11e5-94b0-23a88f5ed021.jpg)

**Comment by devnoname120** [comment]
I only support sites on which the download link is very hard to access (usually requires to untick a checkbox). If a supported site happens to have fake buttons, I remove them along the way, but I will not create a new rule just for hiding elements.
AntiAdware is not designed to replace extensions such as gorhill/uBlock.

**Comment by MED-PRO** [comment]
ok, sorry, thank you anyway
