### ISSUE TITLE
Adobe Flash Player with McAfee still going?! (even AntiAdware installed?!)

### ISSUE THREAD

**Issue by Hans5958** [HandyUserscripts/AntiAdware#27]
Am I only one here who saw this?!

**Comment by devnoname120** [comment]
I have no PC at hand to test this. Have you tried to delete the executable and redownload it from Adobe with AntiAdware activated?

**Comment by Hans5958** [comment]
![wut](https://cloud.githubusercontent.com/assets/11584103/12672636/2a372968-c6aa-11e5-838a-814c7c6560f0.png)

**Comment by devnoname120** [comment]
Is there anything showing in the console? (Ctrl+Shift+J to open it.)

Also, please use the inspector tool on the checkbox and on the rectangular box that is usually hidden and take screenshots.

**Comment by devnoname120** [comment]
@Hans5958 Please try to update GreaseMonkey and this userscript, and tell me if you still have the issue.

**Comment by devnoname120** [comment]
I'm closing this issue since there has been no answer for a long time.
