### ISSUE TITLE
Add chip.de

### ISSUE THREAD

**Issue by IDKwhattoputhere** [HandyUserscripts/AntiAdware#30]
Example: http://www.chip.de/downloads/Maxthon-Cloud-Browser_13008149.html
The real link is x.chip.de while the adware link is a javascript: link.
Installs scareware and other crap.
More info:
https://github.com/gorhill/uBlock/wiki/Badware-risks#chipde
https://github.com/gorhill/uBlock/issues/673

Some off-topic link that might be of interest: https://github.com/reek/anti-adblock-killer/issues/1215
Since Tampermonkey on Android isn't all that great IMO.

Thanks for this awesome piece of software!

**Comment by devnoname120** [comment]
Thank you for telling me about this site, I will try to support it as soon as possible.

**Comment by IDKwhattoputhere** [comment]
It looks like they changed the page and now the download buttons are all gone (https://github.com/uBlockOrigin/uAssets/issues/178#issuecomment-268654446).

**Comment by devnoname120** [comment]
Thank you for letting me know, I will remove it when I get the chance.

**Comment by devnoname120** [comment]
@IDKwhattoputhere I think that I misread your comment. Has Chip stopped to deliver adware altogether? With AntiAdware disabled, I can't find any adware-enabled link here.

**Comment by IDKwhattoputhere** [comment]
Adware is still being delivered. If you're running uBlock Origin it will hide the link now too ([see here](https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt#L24)).
Example: `http://www.chip.de/downloads/W10Privacy_81892989.html`
The adware link is `javascript:DownloadStartInit('141220160956','81892988','')`.
![](https://cloud.githubusercontent.com/assets/16030872/21571206/44749ad2-cecd-11e6-87ef-e0bb652a32f5.png)
It will not be displayed to some users though, mainly Linux users will not see it.

**Comment by devnoname120** [comment]
Would you mind fixing it and sending a pull request? I would like to encourage people to participate in the development of this userscript. You can look at other websites to see how I do things.

Here is the relevant code: https://github.com/HandyUserscripts/AntiAdware/blob/master/AntiAdware.user.js#L145-L154

**Comment by IDKwhattoputhere** [comment]
The script seems to remove the real download link for software where there is no "Chip installer" adware link, e.g: http://www.chip.de/downloads/Firefox-fuer-Linux_23274921.html
Don't really know why.

By the way: Chip.de is owned by [Hubert Burda Media Holding](https://en.wikipedia.org/wiki/Hubert_Burda_Media#Chip) who also own Cliqz which is now shipped in Firefox for 1% of German users.
https://www.ghacks.net/2017/10/06/mozilla-to-launch-firefox-cliqz-experiment-with-data-collecting/
https://www.reddit.com/r/privacy/comments/750vsm/firefox_devs_discussing_how_to_secretly_sneak_the/
http://www.zdnet.com/article/firefox-tests-cliqz-engine-which-slurps-user-browsing-data/
