### ISSUE TITLE
Tampermonkey Dolphin

### ISSUE THREAD

**Issue by maynak00** [HandyUserscripts/AntiAdware#31]
Hi. I can't install userscript to Tampermonkey Dolphin 4.0 (with Install button in tampermonkey.not found in installed userscripts page)
I tried:
https://greasyfork.org/scripts/4294-antiadware/code/AntiAdware.user.js
https://raw.githubusercontent.com/HandyUserscripts/AntiAdware/master/AntiAdware.user.js

**Comment by devnoname120** [comment]
TamperMonkey Dolphin is not a supported engine. Also, this issue doesn't seem to be related to AntiAdware, so you should report your issue here: https://github.com/Tampermonkey/tampermonkey/issues

**Comment by maynak00** [comment]
thanks. I created new issue in tampermonkey issues page. but I can install some other userscripts without problem: http://i.imgbox.com/o3AoI3FV.jpg

**Comment by devnoname120** [comment]
I will close this issue since I don't intend to support Tampermonkey Dolphin.
