### ISSUE TITLE
uploadshub.com (New Website)

### ISSUE THREAD

**Issue by MED-PRO** [HandyUserscripts/AntiAdware#32]
Hi,
uploadshub.com has been changed and there is a new fake download manager button which is checked by default (screenshot)
Tested url: https://uploadshub.com/p47r303yzjk2
Thanks.
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14568502/2dfbd788-0331-11e6-90d2-cacb488a1577.png)

**Comment by devnoname120** [comment]
Oddly, the checkbox is correctly unchecked here.

Which browser and userscript engine are you using? Could you inspect the checkbox and show me its `id`?

**Comment by MED-PRO** [comment]
Okay, I took another screenshot & I'm using Ublock Origin with Firefox 45 and Greasemonkey.
Thanks
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14577363/cd2da7e4-036a-11e6-9d7d-3a7c96471643.png)

**Comment by devnoname120** [comment]
Could you click on the arrow at the left in the highlighted line, and show me what is in here?

**Comment by MED-PRO** [comment]
Okay, as you requested:
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14581645/dd68bcbe-03e9-11e6-9e93-6b32b6513294.png)
![sans titre1](https://cloud.githubusercontent.com/assets/10789454/14581646/e249214c-03e9-11e6-9d8a-e8b8bd598478.png)

**Comment by devnoname120** [comment]
Strange, there is no error in the console.

Could you modify the line o_debug from false to true in the script code and paste the content of the console here?

**Comment by devnoname120** [comment]
@MED-PRO Does it work with the latest version?

**Comment by MED-PRO** [comment]
Please close this issue as the website domain name has changed (see #39)
Regards!

**Comment by devnoname120** [comment]
OK, I will close this issue.
