### ISSUE TITLE
datafilehost.com (broken)

### ISSUE THREAD

**Issue by MED-PRO** [HandyUserscripts/AntiAdware#33]
Hi,
AntiAdware is no longer working with datafilehost.com (screentshot)
Thanks.
Test link: https://www.datafilehost.com/d/291e314b
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14615070/eab98020-059b-11e6-8160-ae3863af44db.png)

**Comment by devnoname120** [comment]
Could you please inspect the download button? Thanks!

**Comment by MED-PRO** [comment]
Okay...
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14617732/3f168162-05a7-11e6-99ff-abc0cc08aa59.png)

**Comment by devnoname120** [comment]
Is there a check box if you disable AntiAdware? Otherwise, is there a way to disable this button from the user side?

**Comment by MED-PRO** [comment]
yes, the check box is checked by default but can be unchecked by user. Enabling or disabling Anti-adware doesn't change anything.

**Comment by devnoname120** [comment]
OK, thank you for the information, I will try to fix this in the coming weeks.

**Comment by DonJuan777** [comment]
What it is its not broken if you switch the link to http  its only broken for https .

**Comment by devnoname120** [comment]
@DonJuan777 Thanks, this is it.

**Comment by MED-PRO** [comment]
This fixed the download manager issue but you won't be able to download the file using "https" !

**Comment by MED-PRO** [comment]
Working fine now. Thank you!
