### ISSUE TITLE
https://www.mirrorcreator.com/files/0L55BBMA/ea057b68b17ea0666c9860131f414f47.rar_links

### ISSUE THREAD

**Issue by BioBrayan** [HandyUserscripts/AntiAdware#35]
https://www.mirrorcreator.com/files/0L55BBMA/ea057b68b17ea0666c9860131f414f47.rar_links
http://i.imgur.com/E3ZANMP.png

Google Chrome 51.0.2704.84
uBlock Origin 1.7.2
Tampermonkey 4.0.69
AntiAdware 1.41.1

please delete this virus and malware download now button

**Comment by devnoname120** [comment]
I support only support sites that by default serve an adware. Here, it is an advertisement that looks like a download button so I won't support it.

You can signal the fake button to people maintaining lists for Adblockers though.
