### ISSUE TITLE
http://go4up.com/dl/1f83ba106d411c

### ISSUE THREAD

**Issue by BioBrayan** [HandyUserscripts/AntiAdware#36]
http://go4up.com/dl/1f83ba106d411c
http://i.imgur.com/atc14mX.png

Google Chrome 51.0.2704.84
uBlock Origin 1.7.2
Tampermonkey 4.0.69
AntiAdware 1.41.1

please delete this virus and malware download button

**Comment by devnoname120** [comment]
I support only support sites that by default serve an adware. Here, it is an advertisement that looks like a download button so I won't support it.

You can signal the fake button to people maintaining lists for Adblockers though.
