### ISSUE TITLE
Jdownloader

### ISSUE THREAD

**Issue by blueeyiz702** [HandyUserscripts/AntiAdware#37]
Can you add this to your list, it's loaded with a ton of adware. Would like to use the app, but can't risk damage to computer. Thank you and here is a link.  http://jdownloader.org/dl?v=101 is actual link that shows up when you click link above. http://fetch.jdcdn.org/download/dl/prepare?l=5&t=1471078446365&v=101&s=gtorahoaoEd9USfvKp0tKPisO%2b9yPVd4ZfGUXD0Zgh8%3d

**Comment by devnoname120** [comment]
Sorry but it isn't practical to do this with a userscript, so I won't support it.
If you find a download page where we can uncheck adware offers in order to get the direct download link, please let me know.
