### ISSUE TITLE
Solidfiles.com is broken (New design)

### ISSUE THREAD

**Issue by MED-PRO** [HandyUserscripts/AntiAdware#38]
Hello
The newly designed Solidfiles.com website is not working with AntiAdware (Screenshot)
Hope you guys fix this
Thank you for your great work!
Regards.
[Tested Link](http://www.solidfiles.com/v/nNVX5ZNrwdy2W)

![sans titre](https://cloud.githubusercontent.com/assets/10789454/17769579/358a05a8-6531-11e6-8e4d-00cd71362dc1.png)
![sans titre1](https://cloud.githubusercontent.com/assets/10789454/17769584/3b678bc6-6531-11e6-8e08-bcd8d3884364.png)

**Comment by devnoname120** [comment]
Thank you for your report.

Can you confirm that there is no more adware on this site?
