### ISSUE TITLE
[Request] backin.net

### ISSUE THREAD

**Issue by adreporter** [HandyUserscripts/AntiAdware#41]
http://backin.net/7sfhxdr7arrz

Please remove this download button:
![przechwytywanie1](https://cloud.githubusercontent.com/assets/18214146/20599334/db765642-b24d-11e6-94c9-e249592a45e7.PNG)

**Comment by devnoname120** [comment]
Hello, I usually don't support sites that only use fake buttons as long as the download is accessible by default, because it would take too much time to maintain, there are just too many sites with a fake download button. Please use a content-filtering extension such as uBlock for this.
