### ISSUE TITLE
remove fake download buttons from  w4files.pw

### ISSUE THREAD

**Issue by swathigrate** [HandyUserscripts/AntiAdware#42]
hello sir ,
   i'm facing small problem with  [w4files.pw](http://w4files.pw/2fe34c5502d4086e) ,,,,  in this  site .. after clicking "free download"   .. showing  two  fake  download  button ..

please  solve this  problem .... 
 
thank you 
![gfg](https://cloud.githubusercontent.com/assets/14991260/20832783/3cb04246-b8b2-11e6-8bb2-7dabe82e12b7.JPG)

**Comment by devnoname120** [comment]
Sorry I don't support sites that only have fake buttons, but whose final link can be accessed without unchecking checkboxes.
