### ISSUE TITLE
chip.de

### ISSUE THREAD

**Issue by Wifrousl** [HandyUserscripts/AntiAdware#54]
hello

https://www.chip.de/download/ instead of https://www.chip.de/downloads/

Greets

**Comment by krystian3w** [comment]
programs have `downloads`

**Comment by Wifrousl** [comment]
I don't know what your problem is, but the problem in the script is still existing.
The right string is:

// @include http*://*chip.de/download/*

and not

// @include http*://*chip.de/downloads/*
