### ISSUE TITLE
Dev-Host (d-h.st) not working

### ISSUE THREAD

**Issue by Arsyadi** [HandyUserscripts/AntiAdware#9]
I can't see downlaod button after update to latest version.

**Comment by devnoname120** [comment]
I can't see anything wrong here.
Here is the test link that I used: http://d-h.st/olE2

![capture](https://cloud.githubusercontent.com/assets/2824100/5606783/463989aa-9440-11e4-977f-3853887ebdf1.PNG)

**Comment by Arsyadi** [comment]
Sorry my bad, now working.
It caused by ABP. 
You can close this case.
